---
AllCops:
  CacheRootDirectory: tmp
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - db/schema.rb
    - bin/*
    - node_modules/**/*
    - Vagrantfile
    - vendor/**/*
    - config/initializers/json_ld*
    - lib/mastodon/migration_helpers.rb
    - lib/templates/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.1
  UseCache: true

inherit_from:
  - .rubocop_todo.yml
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/naming.yml
  - .rubocop/rails.yml
  - .rubocop/rspec-rails.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-capybara
  - ./lib/linter/rubocop_middle_dot
